variable "region"		     { default = "us-east-1"  }                                 // AWS region
variable "profile"		     { default = "default" }      				// AWS credentials profile
variable "name"			     { default = "" }  			                        // EC2 instance name
variable "vpc_id"		     { default = "" }  				                // vpc id
variable "key_name"		     { default = "" }  						// ssh keypair name
variable "subnet_id"		     { default = "" }  						// subnet id
variable "ami"			     { default = "" }  						// ami id
variable "instance_type"	     { default = "" }  						// instance type
variable "private_ip"		     { default = "" }  						// Private ip
variable "sg_name"		     { default = "" }  						// Security group name
variable "source_cidr_block"	     { default = "" }  						// cidr block for ingress rule
variable "ssh_cidr_block"	     { default = "" }  						// ssh cidr block
variable "route_zone_id"	     { default = "" }  						// Route53 zone id
variable "username"		     { default = "cheffer" }  					// Chef server username
variable "first_name"		     { default = "cheffer" }  					// Chef server User Firstname
variable "last_name"		     { default = "admin" }  					// Chef server User Lastname
variable "email_id"		     { default = "nikita.dinavahi@gmail.com" }  		// Chef server User Email id
variable "password"		     { default = "qwerty123" }  				// Chef server User Password
variable "org_name"		     { default = "" }  						// Chef server Organization shortname
variable "full_org_name"	     { default = "" }  						// Chef server Organization fullname
variable "user"			     { default = "ec2-user" }  					// EC2 instance username
variable "private_key"		     { default = "~/.ssh/" }  					// EC2 Private key file location
variable "vpc_cidr_block" 	     { default = "172.16.0.0/16" }				// VPC CIDR block
